language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.8.7
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - ree
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: jruby-head
before_install:
  - gem update --system 2.1.11
  - gem --version
